Repository team-apm/apm-data, pull requests merged in 2021-11, with the labels that each got.

#37 feat: add karoterra packages
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin

#35 feat: support dark themes
  docs/install-script.html
  docs/main.css
Labels: enhancement

#38 fix: add descriptions
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, script

#39 feat: add continuous attribute
  README.en.md
  README.md
  schema/packages_list.xsd
Labels: documentation, enhancement

#40 feat: add LSMASHWorks
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin

#41 ci(nodejs.yml): change to run Node CI on pull requests
  .github/workflows/nodejs.yml
Labels: enhancement

#42 build(deps): update some packages
  package.json
  yarn.lock
Labels: enhancement

#44 feat: specify the dependencies using logical or
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin

#43 feat: add hash to the versions
  data/core.xml
  data/mod.xml
  schema/au.xsd
Labels: enhancement, core

#45 ci(Dependabot): add a Dependabot setting file
  .github/dependabot.yml
Labels: enhancement
