Repository team-apm/apm-data, pull requests merged in 2021-12, with the labels that each got.

#51 Revert integrity v1
  data/core.xml
  data/mod.xml
  schema/au.xsd
Labels: enhancement, core

#52 feat: change ID structure
  v2/data/mod.xml
  v2/data/packages.xml
  v2/schema/packages.xsd
Labels: enhancement, plugin, script

#58 feat: add a version attribute on v1
  data/core.xml
  data/mod.xml
  data/packages_list.xml
  schema/core.xsd
  schema/mod.xsd
  schema/packages_list.xsd
Labels: enhancement

#59 fix: change URLs of GitHub releases
  data/mod.xml
  data/packages_list.xml
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement

#60 ci(GitHub Actions): add automated update check
  .github/workflows/check-update.yml
  package.json
  util/check-update.js
  yarn.lock
Labels: enhancement

#61 feat: add integrity to some libraries
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#62 Fix check update
  .github/workflows/check-update.yml
  util/check-update.js
Labels: enhancement

#68 docs: add contributors in README
  README.en.md
  README.md
Labels: documentation, enhancement

#65 util: add a command to update mod date
  package.json
  util/update-mod.js
Labels: enhancement

#66 feat: add patch.aul and suzune's plugins
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#67 util: add a utility to generate a hash
  .eslintignore
  .eslintrc
  package.json
  util/sri.js
  yarn.lock
Labels: enhancement

#69 feat: add transitions and Maverick Tse plugins
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#70 feat: add rikky packages
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#77 fix: use https
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin, script

#78 feat: add integrity to the archives
  v2/data/core.xml
  v2/data/mod.xml
  v2/data/packages.xml
  v2/schema/core.xsd
  v2/schema/packages.xsd
Labels: enhancement, plugin, core

#81 `convert.json` mod date
  package.json
  util/update-mod.js
  v2/data/mod.xml
  v2/schema/mod.xsd
Labels: enhancement
