Repository team-apm/apm-data, pull requests merged in 2021-09, with the labels that each got.

#5 feat: integrate plugin and script
  data/mod.xml
  data/package.xml
  data/packages_list.xml
  data/script.xml
  data/scripts_list.xml
  schema/au.xsd
  schema/mod.xsd
  schema/package.xsd
  schema/packages_list.xsd
  schema/plugin.xsd
  schema/scripts_list.xsd
Labels: plugin, script

#7 fix: set archivePath to dsinput
  data/packages_list.xml
Labels: plugin

#8 fix: fix the problem that all scripts are uninstalled on uninstalling "拡張編集RAMプレビュー"
  data/packages_list.xml
Labels: bug, plugin

#9 feat: add AviUtlLab packages
  data/packages_list.xml
Labels: plugin

#10 Add a license to this repository
  LICENSE
  README.md
Labels: documentation, enhancement

#11 feat: update the xml structure
  data/core.xml
  data/packages_list.xml
  schema/packages_list.xsd
Labels: enhancement

#12 fix: fixed broken packages
  data/packages_list.xml
Labels: bug, plugin, script

#13 feat: add oov packages
  data/packages_list.xml
Labels: enhancement, plugin, script

#14 update: mod.xml
  data/mod.xml
Labels: enhancement

#15 feat: add rigaya packages
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin

#16 fix: fix a problem that uninstalling x264guiEx/x265guiEx affects other packages
  data/mod.xml
  data/packages_list.xml
Labels: bug, plugin

#17 feat: add yunoimage rikky packages
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin, script

#20 feat(XML Schema): add the dependencies element
  schema/packages_list.xsd
Labels: enhancement

#21 feat: add HTML containing links to scripts
  docs/install-script.html
Labels: enhancement, script

#23 feat: add dependencies tags
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin

#24 feat: add script author
  docs/install-script.html
Labels: enhancement, script

#25 build(deps): update some packages
  yarn.lock
Labels: enhancement

#26 style(lint-staged): make HTML lint in committing
  package.json
Labels: enhancement

#27 feat: add Amazonish and change rikky's link
  docs/install-script.html
Labels: documentation

#28 fix: dependency information
  data/mod.xml
  data/packages_list.xml
Labels: enhancement, plugin
