Repository team-apm/apm-data, pull requests merged in 2022-03, with the labels that each got.

#121 docs: add karoterra in README
  README.en.md
  README.md
Labels: documentation

#120 feat: update patch.aul version
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#111 add installOnly attribute
  README.en.md
  README.md
  v2/data/packages.xml
  v2/schema/au.xsd
Labels: enhancement

#110 feat: data for automatic installation of scripts
  package.json
  util/update-mod.js
  v2/data/mod.xml
  v2/data/packages.xml
  v2/data/scripts.json
  v2/schema/mod.xsd
  v2/schema/scripts.json
Labels: enhancement, plugin, script

#127 fix: fix to patch.aul installation path
  README.en.md
  README.md
  v2/data/mod.xml
  v2/data/packages.xml
  v2/schema/au.xsd
Labels: bug, enhancement, plugin

#133 docs(README): add a jsDelivr badge in README
  README.en.md
  README.md
Labels: documentation

#137 feat: add nure, nazono plugins
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin, script

#145 ci: using node 16
  .github/workflows/nodejs.yml
Labels: enhancement
