Repository team-apm/apm-data, pull requests merged in 2022-05, with the labels that each got.

#171 fix: update Rigaya's packages
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#167 feat(v3): add validation
  package.json
  yarn.lock
Labels: enhancement

#181 feat: add a khsk plugin
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#190 Add nicommons IDs
  package.json
  util/convert-2-3.js
  util/sort.js
  v3/core.json
  v3/list.json
  v3/packages.json
  yarn.lock
Labels: enhancement, plugin, script

#191 feat: update localfont.aul
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#192 util: change to use ESModules
  .eslintrc
  package.json
  util/check-convert.js
  util/check-update.js
  util/convert-2-3.js
  util/sort.js
  util/sri.js
  util/update-mod.js
Labels: enhancement

#198 Migration to ES Modules
  package.json
  util/sri.js
  yarn.lock
Labels: enhancement

#199 ci: add converting v2 to v3 in checking update
  .github/workflows/check-update.yml
  package.json
  util/convert-2-3.js
  v3/list.json
  v3/packages.json
Labels: enhancement

#202 util(convert-2-3): change to log full paths
  util/convert-2-3.js
Labels: enhancement

#203 util(convert-2-3): change to output paths on error
  util/convert-2-3.js
Labels: enhancement

#204 util(convert-2-3): add outputting paths on error
  util/convert-2-3.js
Labels: enhancement

#205 util(convert-2-3): change the way to specify paths
  util/convert-2-3.js
Labels: bug

#207 docs: change the repository owner in README and CONTRIBUTING
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  README.en.md
  README.md
Labels: documentation, enhancement

#211 fix: update MrOjii/LSMASHWorks
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement
