Repository team-apm/apm-data, pull requests merged in 2022-04, with the labels that each got.

#149 refactor: make some XML files strict
  v2/data/core.xml
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin, core

#144 feat: support for data v3
  index.d.ts
  package.json
  v3/data/convert.json
  v3/data/core.json
  v3/data/list.json
  v3/data/packages.json
  v3/data/scripts.json
  v3/schema/core.json
  v3/schema/packages.json
  v3/schema/scripts.json
  v3/types/core.d.ts
  v3/types/packages.d.ts
  v3/types/scripts.d.ts
  yarn.lock
Labels: enhancement

#157 fix: change the download URL of patch.aul
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#159 merge URLs into an array
  v3/data/packages.json
  v3/schema/packages.json
  v3/types/packages.d.ts
Labels: enhancement, plugin, script

#142 feat: add directURL to MrOjii/LSMASHWorks
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin

#166 rafactor: use apm-schema
  index.d.ts
  package.json
  v3/convert.json
  v3/core.json
  v3/list.json
  v3/packages.json
  v3/schema/core.json
  v3/schema/packages.json
  v3/schema/scripts.json
  v3/scripts.json
  v3/types/core.d.ts
  v3/types/packages.d.ts
  v3/types/scripts.d.ts
  yarn.lock
Labels: enhancement, dependencies
