Repository team-apm/apm-data, pull requests merged in 2022-08, with the labels that each got.

#306 chore: change the config of release-it
  .release-it.json
  package.json
Labels: enhancement

#307 util: increase the number of the limit of releases
  util/generate-releases.js
Labels: enhancement

#308 feat: add releases of some packages
  util/archive-name-pattern.json
  v2/data/packages.xml
  v3/packages.json
Labels: enhancement, plugin, script

#323 fix: update the archivePath of suzune/WideDialog
  v3/list.json
  v3/packages.json
Labels: enhancement

#311 util: update utilities for v3
  util/check-convert.js
  util/check-update.js
  util/generate-releases.js
  util/lib/download.js
  util/lib/generateHash.js
  util/lib/unzip.js
  util/sri.js
  util/update-mod.js
Labels: enhancement

#326 Add specification documents
  README.en.md
  README.md
  v1/SPECIFICATION.md
  v1/data/core.xml
  v1/data/mod.xml
  v1/data/packages_list.xml
  v1/schema/au.xsd
  v1/schema/core.xsd
  v1/schema/mod.xsd
  v1/schema/packages_list.xsd
  v2/SPECIFICATION.md
  v3/SPECIFICATION.md
Labels: documentation

#325 ContentsTree・エフェクト並び替え・coord・丸付き折れ線テキストを追加
  v3/packages.json
Labels: enhancement, plugin, script

#328 docs(README): add a contributor's name
  README.en.md
  README.md
Labels: documentation

#329 Update CONTRIBUTING.md
  CONTRIBUTING.en.md
  CONTRIBUTING.ja.md
  CONTRIBUTING.md
  README.en.md
  README.md
Labels: documentation

#334 docs: add a document about Developer ID
  README.en.md
  README.md
  developer-id.md
Labels: documentation
