Repository team-apm/apm-data, pull requests merged in 2022-06, with the labels that each got.

#217 fix: update the directURL of MrOjii/LSMASHWorks
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#220 feat(check-update): update L-SMASH-Works
  .github/workflows/check-update.yml
Labels: enhancement, plugin

#223 fix: updater for l-smash works
  .github/workflows/check-update.yml
  util/check-update.js
Labels: bug, plugin

#227 chore: delete an unnecessary file of 'husky'
  .husky/.gitignore
Labels: enhancement

#228 Improve utilities
  util/check-convert.js
  util/check-update.js
  util/sri.js
  util/update-mod.js
Labels: enhancement

#230 Add creating integrity hash in checking update
  package.json
  util/.gitignore
  util/archive-name-pattern.json
  util/check-update.js
  yarn.lock
Labels: enhancement

#234 feat: update hebiiro packages
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#235 ci: change the owner of the 7-zip files before checking update
  .github/workflows/check-update.yml
Labels: enhancement

#244 feat: update audio-related plugins
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#249 feat: add UniteWindow
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#261 feat: add shummg/textmodule
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#262 util: add a generator of releases
  package.json
  util/generate-releases.js
Labels: enhancement

#245 feat: package sets
  docs/empty.zip
  docs/package-sets-description.html
  v3/list.json
  v3/package-sets.json
Labels: enhancement, plugin
