Repository team-apm/apm-data, pull requests merged in 2022-02, with the labels that each got.

#102 fix: dependency priorities
  v2/data/mod.xml
  v2/data/packages.xml
Labels: bug, plugin

#103 feat: add karoterra packages
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin, script

#104 feat: update packages (Feb. 2022)
  v2/data/mod.xml
  v2/data/packages.xml
Labels: enhancement, plugin, script

#109 fix: fllow xml parser changes
  util/check-update.js
Labels: bug
