Repository team-apm/apm-data, pull requests merged in 2022-07, with the labels that each got.

#260 feat: add shummg's site
  v2/data/mod.xml
  v2/data/packages.xml
  v2/data/scripts.json
  v3/list.json
  v3/packages.json
  v3/scripts.json
Labels: enhancement, plugin, script

#265 feat: add tetsu(xiao)'s script
  v2/data/packages.xml
  v3/packages.json
Labels: enhancement, script

#266 feat: add AviUtl-svg
  v2/data/packages.xml
  v3/packages.json
Labels: enhancement, script

#269 feat: add the ePi plugins
  v2/data/packages.xml
  v3/packages.json
Labels: enhancement, plugin

#270 feat: add tim's scripts
  v2/data/mod.xml
  v2/data/scripts.json
  v3/list.json
  v3/packages/tim.json
  v3/scripts.json
Labels: enhancement, script

#279 feat: add hebiiro's SplitWindow
  util/archive-name-pattern.json
  v2/data/mod.xml
  v2/data/packages.xml
  v3/list.json
  v3/packages.json
Labels: enhancement, plugin

#294 build(deps-dev): add release-it
  .release-it.json
  package.json
  yarn.lock
Labels: enhancement
