Repository team-apm/apm-data, pull requests merged in 2025-02, with the labels that each got.

#828 fix: update MrOjii/LSMASHWorks
  v3/packages.json
Labels: enhancement, plugin

#829 feat: add hebiiro/ultimate plugin
  v3/packages.json
Labels: enhancement, plugin

#875 fix: change lsmashworks location
  v3/list.json
  v3/packages.json
Labels: bug, enhancement, plugin

#883 build(deps-dev): bump dependencies
  docs/main.css
  package.json
  yarn.lock
Labels: dependencies
